# Generated by Django 2.2.11 on 2020-03-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charity',
            name='rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='charity',
            name='addr',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='charity',
            name='city',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='charity',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
